### PR TITLE
docs: update fswatch example to use dune exec -w

### PR DESCRIPTION
**Pull request by dangdennis**
Since fswatch isn't used anymore, I've renamed the example to `w-watch-mode`. It's now just a nice little tip for anyone getting started with dune and dream. 

~~R esolves https://github.com/aantron/dream/issues/81~~

### CODE REVIEW

**Comment by aantron** [comment]
Thank you!

I undid the directory move to help git understand the history. When one combines a massive rewrite (like the README in this PR) together with a renaming, git thinks that a file was deleted and a new one was created. I left the rewriting in this PR, and I'll do the renaming in a separate commit after this PR, and also update all the links to the example from the README and the example index.

**Comment by dangdennis** [comment]
Awesome. I’ll do the git mv manually next time then. 😂 high bar for git cleanliness here.

**Comment by dangdennis** [comment]
great catch on the links.

**Comment by aantron** [comment]
> Awesome. I’ll do the git mv manually next time then. 😂 high bar for git cleanliness here.

Yeah I too often have to dig in git history and the cleaner it is the easier it is in the future, git history is like a form of documentation, especially when you eventually are able to reach the various PRs that caused something. There is often a lack of comments in the code but plenty of discussion in the PR. So it helps the archaelogy to keep the history clear :)

**Pull request merged**
