### PR TITLE
Add community projects list to README

### PR DESCRIPTION
**Pull request by tmattio**
Adding some community projects. I did a quick search on Github to see if there were others but didn't find any. Hopefully soon 🙂 

I'm not sure what the threshold should be for a project to be on this list. `dream-livereload` and `dream-cli` should be usable, but `dream-analytics` is very bare bone for now. Let me know if I should remove it from the list.

### CODE REVIEW

**Comment by aantron** [comment]
Thanks for starting this! I suggest removing `dream-analytics` because it is bare-bones, and `dream-serve` because it's just a user of Dream. I'd like to keep this as a list of ready libraries to use *with* Dream. Maybe Dream will have a separate users list somewhere, later.

**Comment by tmattio** [comment]
I removed `dream-serve` and `dream-analytics` (hopefully the latter will come back on the list soon 🤞). This is ready to go if you want.

**Comment by tmattio** [comment]
@aantron I added READMEs to all of the projects (`dream-cli`, `dream-livereload` and `dream-encoding`), and they are released on Opam (PR pending). Let me know if there's anything else you'd like to improve before merging this.

**Comment by aantron** [comment]
Thanks, I'll monitor the opam PRs and take over from here!

**Comment by aantron** [comment]
Thanks! Looks like the projects are ready.

dream-encoding will need a little work to make it streaming. However, part of that work is on the Dream side and Dream's fault :)

**Pull request merged**
