### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by maxRN**
This PR fixes the pipeline to enable running tests again on Ubuntu and MacOS on OCaml verions 4.14.x and 5.0.x.

Windows builds require some more special attention. There were some errors during compilation of the ssl dependency. Logs can be found here: https://github.com/maxRN/dream/actions/runs/10508356669/job/29112078780

The Mirage tests are also failing, because of some dependency issues which I didn't have time to investigate further. Logs for those can be found here: https://github.com/maxRN/dream/actions/runs/10521553562/job/29152441822 (the other, non-mirage test failures can be ignored - I was just testing something in this run)

### CODE REVIEW

**Comment by maxRN** [comment]
Ping @aantron. Are you okay with merging this even if it's just for Ubuntu/MacOS? I don't think we should block this, because I don't know how much more work getting Windows and Mirage tests to work will be. A working CI pipeline, even if it's just a subset, is worth a lot imo.

**Comment by aantron** [comment]
Yes, thank you very much! If you're done with this, I'd probably merge it by cherry-picking the net diff (with due credit, into commits with your authorship on them), and continuing with my additional attempts to get it all working/decide to accept allowed failures for some rows.

**Comment by aantron** [comment]
Great, thank you again, this is a lot of very helpful work!

I'll leave it open and probably open another PR that will incorporate this work (with due credit), and that PR will close this one when merged.

**Comment by aantron** [comment]
(The reason for cherry-picking the net diff is just to try to uncomment the Mirage build, etc., so that if I can get them working, the diff doesn't cause spurious blame on those lines -- I'll figure out the right history at the end of trying to get it all to work)

**Comment by maxRN** [comment]
Yeah makes sense, but honestly if it's too much work getting the commit history in order you can also just copy my changes and commit them yourself. I don't mind if the commits aren't "properly" credited to me -- I don't plan on those being my last contributions 😄

**Comment by aantron** [comment]
The issue with package `ssl` on Windows is caused somewhere upstream, by either `ssl`, `setup-ocaml`, or elsewhere. I've opened https://github.com/savonet/ocaml-ssl/issues/155 and https://github.com/savonet/ocaml-ssl/pull/156 about that. For now, I'll try pinning `ssl` to an older version or disabling the Windows build, both regrettable options.

**Comment by aantron** [comment]
Mirage build looks like it needs https://github.com/robur-coop/ocaml-letsencrypt/pull/34, which is awaiting release of https://github.com/ocaml/opam-repository/pull/26454. Probably better to just ping and wait for that.

**Comment by aantron** [comment]
Amazing. Thank you!

**Pull request merged**
