### PR TITLE
Unvendor everything except paf for esy

### PR DESCRIPTION
**Pull request by ulrikstrid**
This should in theory allow us to use Piaf and other things together with Dream if we're using esy (and potentially nix)

### CODE REVIEW

**Comment by aantron** [comment]
Thanks!

**Comment by dinosaure** [comment]
Not sure that it's the correct way to do to still be installable _via_ `opam`.

**Comment by ulrikstrid** [comment]
@dinosaure this is on a separate branch, the "real" solution would be if @anmonteiro's work could be upstreamed and/or released.

**Comment by aantron** [comment]
I've since first renamed the vendored libraries, and now replaced them with depending on httpun. Do we still need the `esy-unvendor` branch?

**Comment by ulrikstrid** [comment]
I don't think so. The branch is also very outdated so it likely doesn't make sense to use either way.

**Pull request merged**
